export const API = {
  BASE_URL: import.meta.env.VITE_API_URL || 'https://api.tvmaze.com',
  RATE_LIMIT_DELAY: 1100,
  ENDPOINTS: {
    SHOWS: '/shows',
  },
} as const

export const GENRES: string[] = [
  'Action',
  'Adventure',
  'Adult',
  'Anime',
  'Children',
  'Comedy',
  'Crime',
  'DIY',
  'Drama',
  'Espionage',
  'Fantasy',
  'Family',
  'Food',
  'History',
  'Horror',
  'Legal',
  'Medical',
  'Mystery',
  'Music',
  'Nature',
  'Romance',
  'Science-Fiction',
  'Sports',
  'Supernatural',
  'Thriller',
  'Travel',
  'War',
  'Western',
]
